config/routes.rb
Rails.application.routes.draw do
  get "/", to: "rooms#index", as: "root"
  devise_for :users
  #Room routes
  resources :rooms
  resources :room_messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user, required: false
  has_many :room_messages, dependent: :destroy,
                          inverse_of: :room
  validates :title, presence: true
end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  belongs_to :user
  belongs_to :room, inverse_of: :room_messages

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, uniqueness: true, presence: true
  has_many :rooms
  has_one_attached :avatar
  has_many :room_messages, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :avatar, :biography])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home()
  end
end

app/controllers/room_messages_controller.rb
class RoomMessagesController < ApplicationController
  before_action :load_entities

  def create
    p "**********"
    p params
    p "**********"

    @room_message = current_user.room_messages.create(messages_params)
    redirect_back(fallback_location: root_path)
  end

  # he has this code too
  #   RoomChannel.broadcast_to @room, @room_message
  # end
  #^ after we get ActionCable and wewbsockets
  #ok cool!

  protected

  def load_entities
    @room = current_user.rooms.find_by_id(params[:id])
  end

  private

  def messages_params
    params.require(:room_message).permit(:user_id, :room_id, :description)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
    @room_message = RoomMessage.new room: @room
    @room_messages = @room.room_messages.includes(:user)
  end

  def new
    @room = Room.new
  end

  def create
    @room = current_user.rooms.create(rooms_params)
    if @room.errors.any?
      render "new"
    else
      redirect_to root_path
    end
  end

  def edit
    @room = current_user.rooms.find_by_id(params[:id])

    if @room
      render "edit"
    else
      redirect_to root_path
    end
  end

  def update
    @room = current_user.rooms.find_by_id(params[:id])

    if @room
      @room.update(rooms_params)
      if @room.errors.any?
        render "edit"
      else
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end

  def destroy
    Room.find(params[:id]).destroy
  end
end

private

def set_room
  id = params[:id]
  @room = Room.find(id)
end

def rooms_params()
  params.require(:room).permit(:title)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>T2Hackaton</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
    <%= render "shared/navigation_bar" %>
    <%= render "shared/alerts" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
Home Page

app/views/rooms/_form.html.erb
<% if room.errors.any? %>
    <ul>
        <% room.errors.full_messages.each do |error| %>
            <li><%= error %></li>
        <% end %>
    </ul>
<% end %>

<%= form_with model: room, local: true do |f| %>
<div>
    <%= f.label :title %>
    <%= f.text_field :title, value: room.title %>
</div>
<%= f.submit "Create a Room", class: "button is-primary" %>

<% end %>

app/views/rooms/_room.html.erb
<div class="columns is-mobile is-centered">
    <div class="column is-centered">
        <p class="bd-notification is-primary">
            <%= link_to "Create Room", new_room_path, class: "button is-primary button is-large" %>
            <br>
        </p>
    </div>
</div>
<div class="columns is-centered">
    <table class="table is-striped is-hoverable " style="width: 900px;">
        <tr class="th">
            <th>Current Boards</th>
        </tr>
        <% if @rooms.present? %>
        <nav class="flex-column is-four-fifths">
            <% for room in @rooms %>
            <tr>
                <td class="post"><%= link_to room.title, room_path(room) %></td>
            </tr>
            <br>
            <% end %>
        </nav>
        <% else %>
        <div class="text-muted">
            There are no rooms
        </div>
        <% end %>
</div>
</table>

app/views/rooms/edit.html.erb
<h1> Edit Room </h1>

<%= render 'form', room: @room %>

app/views/rooms/index.html.erb
<h1>Hello! Let's Chat.</h1>

<%= render "room" %>

app/views/rooms/new.html.erb
<h1 class="title">New Room</h1>
<div class= "columns is-centered">
<%= render 'form', room: @room%>
</div>

app/views/rooms/show.html.erb
<section class="container">
    <div class="columns">
    <% # Room Heading %>
        <div class="column is-one-quarter">
            <h1> <%= @room.title %> </h1>
        </div>
    <% # Room List %>

    <% # Message chat box %>
    <% # Messages %>
        <div class="column is-three-quarters" id="chat-box" style="background-color: aqua">
        <% # Render chat messages %>
            <% @room_messages.each do |room_message| %>
            <div>
                        <%= room_message.description %>
                </div>
                <small>
                            <%= room_message.created_at %>
                </small>
            <% end %>
                </div> 
        </div>
        <% # Message form %>
        <%= form_with model: @room_message, local: true do |f| %>
        <div class="input">
            <%= f.hidden_field :room_id, value: @room.id %>
            <%= f.label :message %>
            <%= f.text_field :description, value: @room_message.description %>
        </div>
        <%= f.submit "Send", class: "button is-primary" %>
        <% end %>
</section>

app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_navigation_bar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <h1> Hello Chatworld</h1>
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
     <%= link_to "Home", root_path, class: "navbar-item" %>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
          <% if user_signed_in? %>
      
        <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          <%= current_user.email %>
        </a>
        <div class="navbar-dropdown">
            <%= link_to "Edit", edit_user_registration_path, class: "navbar-item" %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-item" %>
        </div>
      </div>
        <% else %>
        <div class="buttons">
          <%= link_to "Sign Up", new_user_registration_path, class: "button is-primary" %>
          <%= link_to "Log In", new_user_session_path, class: "button is-light" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</nav>